source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/lombok-1.18.24.jar,\
               lib/approvaltests-util-29.0.0.jar,\
               testlib/assertj-core-3.13.2.jar,\
               testlib/jackson-annotations-2.10.2.jar,\
               testlib/jackson-core-2.10.2.jar,\
               testlib/jackson-databind-2.10.2.jar,\
               res/icons/approved_all_text_16.png,\
               res/icons/approved_text_16.png,\
               res/icons/compare_text_16.png
src.includes = res/,\
               test-resources/,\
               lib/,\
               testlib/
src.excludes = res/icons/approve.png,\
               res/icons/approve_doc.png,\
               res/icons/approve_doc_solid.png,\
               res/icons/approve_multi.png,\
               res/icons/approved_all_text_32.png,\
               res/icons/approved_text_32.png,\
               res/icons/compare_text_32.png,\
               res/icons/red_green.png
